"""empty message

Revision ID: 19a7401bb0fc
Revises: b1c605f46809
Create Date: 2020-11-17 21:01:30.489421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a7401bb0fc'
down_revision = 'b1c605f46809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stalked_page', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stalked_page', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stalked_page', type_='foreignkey')
    op.drop_column('stalked_page', 'user')
    # ### end Alembic commands ###
